version: '3.3'

services:
  py:
    container_name: text_finder
    build: .
    depends_on:
      - redis
    #tty: true
    command: "python video_processor.py"
    volumes:
      - ./app:/usr/src/app
      - ./input:/input
      - ./output:/output
    environment:
      REDIS_HOST: redis
      REDIS_PASS: unP4ssW0rdParaPOCs
      REDIS_PORT: 6379
  redis:
    image: redis:6.2.6
    command: redis-server --requirepass unP4ssW0rdParaPOCs
    ports:
      - '6379:6379'
